# Default values for sample-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
algo: "nana"
image:
  repository: pgfsw/nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: v0.2.0

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: LoadBalancer
  port: 80


## Application level settings  
appMode: staging
certificatePath: /etc/ssl/staging
paypalURLLocation: https://staging.paypal.example.com
databaseUser: staging-user
databasePassword: staging-password




